name: caffeine
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.2
  google_fonts: ^6.3.2
  supabase_flutter: ^2.10.3 
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^9.1.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.3
  carousel_slider: ^5.1.1
  font_awesome_flutter: ^10.12.0
  dio: ^5.9.0
  image_picker: ^1.2.1
  cloudinary_public: ^0.23.1
  skeletonizer: ^2.1.1
  intl: ^0.20.2
  freezed_annotation: ^3.1.0
  cached_network_image: ^3.4.1
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  flutter_paymob: ^1.0.8


dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/pnga/
    - assets/svgs/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
